import FWCore.ParameterSet.Config as cms

process = cms.Process("TriggerMatching")

### GlobalTag                                                                                                                                                                                                                                                                 
process.load('Configuration/StandardSequences/FrontierConditions_GlobalTag_cff')

process.GlobalTag.globaltag = 'PRE_LS171V9A::All'

process.load( "FWCore.MessageService.MessageLogger_cfi" )

process.MessageLogger.cerr.FwkReport.reportEvery = 2000

process.maxEvents = cms.untracked.PSet(input = cms.untracked.int32(-1))

process.source = cms.Source(

    "PoolSource",

    fileNames = cms.untracked.vstring(

'/store/user/mirena/TT_Spring14/outputFULL_100_2_ltb.root',
'/store/user/mirena/TT_Spring14/outputFULL_107_1_tOX.root',
'/store/user/mirena/TT_Spring14/outputFULL_108_1_GZs.root',
'/store/user/mirena/TT_Spring14/outputFULL_109_1_DwQ.root',
'/store/user/mirena/TT_Spring14/outputFULL_10_1_6LG.root',
'/store/user/mirena/TT_Spring14/outputFULL_110_1_MGp.root',
'/store/user/mirena/TT_Spring14/outputFULL_111_1_PcS.root',
'/store/user/mirena/TT_Spring14/outputFULL_112_1_A92.root',
'/store/user/mirena/TT_Spring14/outputFULL_113_1_NCM.root',
'/store/user/mirena/TT_Spring14/outputFULL_114_1_bop.root',
'/store/user/mirena/TT_Spring14/outputFULL_115_1_a9S.root',
'/store/user/mirena/TT_Spring14/outputFULL_116_1_PKW.root',
'/store/user/mirena/TT_Spring14/outputFULL_117_1_T8w.root',
'/store/user/mirena/TT_Spring14/outputFULL_118_1_SRC.root',
'/store/user/mirena/TT_Spring14/outputFULL_119_1_2Nq.root',
'/store/user/mirena/TT_Spring14/outputFULL_120_1_UJh.root',
'/store/user/mirena/TT_Spring14/outputFULL_121_1_5Pj.root',
'/store/user/mirena/TT_Spring14/outputFULL_122_1_o2P.root',
'/store/user/mirena/TT_Spring14/outputFULL_124_1_wJF.root',
'/store/user/mirena/TT_Spring14/outputFULL_126_1_keo.root',
'/store/user/mirena/TT_Spring14/outputFULL_127_1_HdG.root',
'/store/user/mirena/TT_Spring14/outputFULL_128_1_08Q.root',
'/store/user/mirena/TT_Spring14/outputFULL_129_1_G2w.root',
'/store/user/mirena/TT_Spring14/outputFULL_12_1_03i.root',
'/store/user/mirena/TT_Spring14/outputFULL_132_1_N9o.root',
'/store/user/mirena/TT_Spring14/outputFULL_134_1_CB1.root',
'/store/user/mirena/TT_Spring14/outputFULL_135_1_aur.root',
'/store/user/mirena/TT_Spring14/outputFULL_137_1_QRB.root',
'/store/user/mirena/TT_Spring14/outputFULL_138_1_l9I.root',
'/store/user/mirena/TT_Spring14/outputFULL_139_1_0XQ.root',
'/store/user/mirena/TT_Spring14/outputFULL_13_1_3kA.root',
'/store/user/mirena/TT_Spring14/outputFULL_140_1_OXe.root',
'/store/user/mirena/TT_Spring14/outputFULL_142_1_tXy.root',
'/store/user/mirena/TT_Spring14/outputFULL_143_1_zBL.root',
'/store/user/mirena/TT_Spring14/outputFULL_144_1_VN4.root',
'/store/user/mirena/TT_Spring14/outputFULL_146_1_x12.root',
'/store/user/mirena/TT_Spring14/outputFULL_147_1_iGC.root',
'/store/user/mirena/TT_Spring14/outputFULL_148_1_YIO.root',
'/store/user/mirena/TT_Spring14/outputFULL_149_1_fyU.root',
'/store/user/mirena/TT_Spring14/outputFULL_14_1_qIN.root',
'/store/user/mirena/TT_Spring14/outputFULL_150_1_hLr.root',
'/store/user/mirena/TT_Spring14/outputFULL_151_1_vDN.root',
'/store/user/mirena/TT_Spring14/outputFULL_152_1_UtL.root',
'/store/user/mirena/TT_Spring14/outputFULL_153_1_GCj.root',
'/store/user/mirena/TT_Spring14/outputFULL_154_1_0fn.root',
'/store/user/mirena/TT_Spring14/outputFULL_156_1_vOJ.root',
'/store/user/mirena/TT_Spring14/outputFULL_157_1_SZR.root',
'/store/user/mirena/TT_Spring14/outputFULL_158_1_3R7.root',
'/store/user/mirena/TT_Spring14/outputFULL_159_1_Bub.root',
'/store/user/mirena/TT_Spring14/outputFULL_15_2_c3i.root',
'/store/user/mirena/TT_Spring14/outputFULL_161_1_hkw.root',
'/store/user/mirena/TT_Spring14/outputFULL_162_1_CJw.root',
'/store/user/mirena/TT_Spring14/outputFULL_164_1_qMw.root',
'/store/user/mirena/TT_Spring14/outputFULL_166_1_5dZ.root',
'/store/user/mirena/TT_Spring14/outputFULL_168_1_8zY.root',
'/store/user/mirena/TT_Spring14/outputFULL_171_1_oiU.root',
'/store/user/mirena/TT_Spring14/outputFULL_173_1_Dts.root',
'/store/user/mirena/TT_Spring14/outputFULL_174_1_loA.root',
'/store/user/mirena/TT_Spring14/outputFULL_175_1_x06.root',
'/store/user/mirena/TT_Spring14/outputFULL_177_1_l6Q.root',
'/store/user/mirena/TT_Spring14/outputFULL_179_1_HSD.root',
'/store/user/mirena/TT_Spring14/outputFULL_180_1_UFc.root',
'/store/user/mirena/TT_Spring14/outputFULL_181_1_muW.root',
'/store/user/mirena/TT_Spring14/outputFULL_182_1_5uD.root',
'/store/user/mirena/TT_Spring14/outputFULL_184_1_xB2.root',
'/store/user/mirena/TT_Spring14/outputFULL_185_1_wy2.root',
'/store/user/mirena/TT_Spring14/outputFULL_186_1_uUY.root',
'/store/user/mirena/TT_Spring14/outputFULL_187_1_pGg.root',
'/store/user/mirena/TT_Spring14/outputFULL_188_1_YPd.root',
'/store/user/mirena/TT_Spring14/outputFULL_189_1_YJq.root',
'/store/user/mirena/TT_Spring14/outputFULL_190_1_z30.root',
'/store/user/mirena/TT_Spring14/outputFULL_191_1_dhp.root',
'/store/user/mirena/TT_Spring14/outputFULL_192_1_HrI.root',
'/store/user/mirena/TT_Spring14/outputFULL_193_1_QT9.root',
'/store/user/mirena/TT_Spring14/outputFULL_194_1_ljz.root',
'/store/user/mirena/TT_Spring14/outputFULL_196_1_Q4G.root',
'/store/user/mirena/TT_Spring14/outputFULL_197_1_Gw6.root',
'/store/user/mirena/TT_Spring14/outputFULL_198_1_x88.root',
'/store/user/mirena/TT_Spring14/outputFULL_199_1_Aez.root',
'/store/user/mirena/TT_Spring14/outputFULL_19_1_RFH.root',
'/store/user/mirena/TT_Spring14/outputFULL_1_1_DnI.root',
'/store/user/mirena/TT_Spring14/outputFULL_200_1_Uix.root',
'/store/user/mirena/TT_Spring14/outputFULL_201_1_eNz.root',
'/store/user/mirena/TT_Spring14/outputFULL_20_1_X9V.root',
'/store/user/mirena/TT_Spring14/outputFULL_21_2_Vay.root',
'/store/user/mirena/TT_Spring14/outputFULL_22_1_FIw.root',
'/store/user/mirena/TT_Spring14/outputFULL_23_1_vWY.root',
'/store/user/mirena/TT_Spring14/outputFULL_24_1_kMA.root',
'/store/user/mirena/TT_Spring14/outputFULL_25_1_rJU.root',
'/store/user/mirena/TT_Spring14/outputFULL_26_1_sln.root',
'/store/user/mirena/TT_Spring14/outputFULL_27_2_rsR.root',
'/store/user/mirena/TT_Spring14/outputFULL_28_1_iE1.root',
'/store/user/mirena/TT_Spring14/outputFULL_29_1_bax.root',
'/store/user/mirena/TT_Spring14/outputFULL_2_1_D2Z.root',
'/store/user/mirena/TT_Spring14/outputFULL_30_1_u2z.root',
'/store/user/mirena/TT_Spring14/outputFULL_31_1_yyj.root',
'/store/user/mirena/TT_Spring14/outputFULL_32_1_J3g.root',
'/store/user/mirena/TT_Spring14/outputFULL_33_1_xt7.root',
'/store/user/mirena/TT_Spring14/outputFULL_34_1_78G.root',
'/store/user/mirena/TT_Spring14/outputFULL_35_1_AAj.root',
'/store/user/mirena/TT_Spring14/outputFULL_36_1_o1c.root',
'/store/user/mirena/TT_Spring14/outputFULL_37_1_oxf.root',
'/store/user/mirena/TT_Spring14/outputFULL_38_1_t1I.root',
'/store/user/mirena/TT_Spring14/outputFULL_39_2_UBx.root',
'/store/user/mirena/TT_Spring14/outputFULL_3_1_Tpm.root',
'/store/user/mirena/TT_Spring14/outputFULL_40_1_6Oq.root',
'/store/user/mirena/TT_Spring14/outputFULL_41_1_Agg.root',
'/store/user/mirena/TT_Spring14/outputFULL_42_1_Gtb.root',
'/store/user/mirena/TT_Spring14/outputFULL_43_1_Qgt.root',
'/store/user/mirena/TT_Spring14/outputFULL_44_1_Ju7.root',
'/store/user/mirena/TT_Spring14/outputFULL_45_1_RCr.root',
'/store/user/mirena/TT_Spring14/outputFULL_47_1_HVm.root',
'/store/user/mirena/TT_Spring14/outputFULL_48_1_GD9.root',
'/store/user/mirena/TT_Spring14/outputFULL_49_1_mid.root',
'/store/user/mirena/TT_Spring14/outputFULL_4_1_VRT.root',
'/store/user/mirena/TT_Spring14/outputFULL_50_1_YLL.root',
'/store/user/mirena/TT_Spring14/outputFULL_51_1_SaT.root',
'/store/user/mirena/TT_Spring14/outputFULL_52_2_B25.root',
'/store/user/mirena/TT_Spring14/outputFULL_53_1_2lU.root',
'/store/user/mirena/TT_Spring14/outputFULL_55_1_b4T.root',
'/store/user/mirena/TT_Spring14/outputFULL_57_1_3JL.root',
'/store/user/mirena/TT_Spring14/outputFULL_59_2_ORT.root',
'/store/user/mirena/TT_Spring14/outputFULL_5_1_Jl1.root',
'/store/user/mirena/TT_Spring14/outputFULL_61_2_EUg.root',
'/store/user/mirena/TT_Spring14/outputFULL_63_1_cH8.root',
'/store/user/mirena/TT_Spring14/outputFULL_64_1_vIP.root',
'/store/user/mirena/TT_Spring14/outputFULL_65_1_d4e.root',
'/store/user/mirena/TT_Spring14/outputFULL_67_2_W4P.root',
'/store/user/mirena/TT_Spring14/outputFULL_68_1_OtG.root',
'/store/user/mirena/TT_Spring14/outputFULL_69_1_c1O.root',
'/store/user/mirena/TT_Spring14/outputFULL_6_1_Yx7.root',
'/store/user/mirena/TT_Spring14/outputFULL_70_2_4Xr.root',
'/store/user/mirena/TT_Spring14/outputFULL_71_1_L2F.root',
'/store/user/mirena/TT_Spring14/outputFULL_73_1_aE9.root',
'/store/user/mirena/TT_Spring14/outputFULL_74_1_Jbi.root',
'/store/user/mirena/TT_Spring14/outputFULL_76_1_vW8.root',
'/store/user/mirena/TT_Spring14/outputFULL_77_1_IYx.root',
'/store/user/mirena/TT_Spring14/outputFULL_78_1_6YK.root',
'/store/user/mirena/TT_Spring14/outputFULL_7_1_S9X.root',
'/store/user/mirena/TT_Spring14/outputFULL_80_1_m9V.root',
'/store/user/mirena/TT_Spring14/outputFULL_81_1_SiC.root',
'/store/user/mirena/TT_Spring14/outputFULL_82_1_LIk.root',
'/store/user/mirena/TT_Spring14/outputFULL_83_1_QJz.root',
'/store/user/mirena/TT_Spring14/outputFULL_84_1_OxU.root',
'/store/user/mirena/TT_Spring14/outputFULL_85_1_NOR.root',
'/store/user/mirena/TT_Spring14/outputFULL_87_1_8Sp.root',
'/store/user/mirena/TT_Spring14/outputFULL_88_1_BAk.root',
'/store/user/mirena/TT_Spring14/outputFULL_89_1_X6j.root',
'/store/user/mirena/TT_Spring14/outputFULL_8_1_By3.root',
'/store/user/mirena/TT_Spring14/outputFULL_90_1_qQb.root',
'/store/user/mirena/TT_Spring14/outputFULL_91_2_DN9.root',
'/store/user/mirena/TT_Spring14/outputFULL_92_1_s90.root',
'/store/user/mirena/TT_Spring14/outputFULL_93_1_j89.root',
'/store/user/mirena/TT_Spring14/outputFULL_94_1_spI.root',
'/store/user/mirena/TT_Spring14/outputFULL_95_1_3ig.root',
'/store/user/mirena/TT_Spring14/outputFULL_96_1_rBm.root',
'/store/user/mirena/TT_Spring14/outputFULL_99_2_C2y.root',
'/store/user/mirena/TT_Spring14/outputFULL_9_1_Exk.root',


        )

    )

process.TFileService = cms.Service( "TFileService",

                                    fileName = cms.string( 'analyzeRECO.root' )
                                    )

process.TriggerMatching = cms.EDAnalyzer('TriggerMatching',
                                         muPtCut = cms.double(8.0),
                                         muEtaCut = cms.double(2.4),
                                         ##isoCut = cms.double(0.2),
                                         primaryVertexInputTag = cms.InputTag("offlinePrimaryVertices"),
                                         elePtCut =  cms.double(8.0),
                                         eleEtaCut =  cms.double(2.5),

                                         #full5x5SigmaIEtaIEtaMap = cms.InputTag("electronIDValueMapProducer:eleFull5x5SigmaIEtaIEta"),
                                         #electronIDs = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-CSA14-PU20bx25-V0-standalone-medium"),

)

process.p= cms.Path(process.TriggerMatching)
